### ISSUE TITLE
Implementation of Video Speed Control

### ISSUE THREAD

**Issue by adrchlik** [jvcleave/ofxOMXPlayer#10]
Hi jvcleave,
I want to ask if it is possible to add there function to adjust current video speed. It would be nice if I can sometimes to slow down or speed up the video playing speed.
Is it difficult to do that ?

**Comment by smarques** [comment]
+1 for speed control

**Comment by jvcleave** [comment]
There are some speed options 

https://github.com/jvcleave/ofxOMXPlayer/blob/master/src/ofxOMXPlayer.h#L49

**Comment by smarques** [comment]
It would be nice to have a finer grain speed control, now you can only use integer multipliers. but for some applications I think it would be very useful to use a decimal value.. something along these lines:
https://github.com/huceke/omxplayer/commit/8e182bea20ad074ddf50ae7f8b1095c8cd7ef419

In fact I am trying to implement that, do you have any suggestions?
Thank you

**Comment by jvcleave** [comment]
@smarques those are all actually hardcoded/set values, the S Macro takes the floating point number and translates it into a Q16 value (the hardware clock doesn't understand floats). You can see it is just using a table with `SetSpeed(playspeeds[playspeed_current]);` i

**Comment by jvcleave** [comment]
https://en.wikipedia.org/wiki/Q_(number_format)

**Comment by smarques** [comment]
Jason yes,I get that. Still I am confused on how to do the same thing with the current ofxOmxPlayer.
Is there a way to control player speed (including for example setting it to 0.5 or 0.25) directly from ofxOmxPlayer?
And if not do you have any suggestion on how to add this functionality?

**Comment by smarques** [comment]
Ok, after a deeper look at the code, to me it looks like it would be easy to add a function like setSpeedPercentage(int newPercentage) to the player and to the playerEngine class.
The function on the playerEngine just multiplies the defaultSpeed by a custom percentage and rounds it to int.
It seems to work for me, do you see any potential problems?
