### ISSUE TITLE
Disabling the player

### ISSUE THREAD

**Issue by itzaks** [jvcleave/ofxOMXPlayer#100]
Hello!

Wonderful work with the OMXPlayer. Really stoked to see my old PI1 B+ handling multiple videos plus shaders on a steady 60fps. 

I try to achieve switching visibility between multiple players in realtime. It seems the fastest way to do this is to keep them playing and control which one is being drawn (to my shader). 

 This way it seems as a waste of resources to have invisible players running in the background. Is it possible to disable / enable them frictionless? When I pause them I experience a bit of a delay upon playing them again.

**Comment by jvcleave** [comment]
Not sure the best way to do it out-of-the-box. Pausing it should stop most of the processing but you may need to do some modifications - maybe write something that makes the threads sleep (if they are still running) on pause?

**Comment by itzaks** [comment]
Okay, thanks for the quick response. I'll look into it :) On a little sidenote, is it possible to pass the stream from ofxOMXRecorder to ofxOMXPlayer without writing to disk, keeping it in memory?

**Comment by jvcleave** [comment]
Not really as ofxOMXPlayer uses ffmpeg/libav to probe the file to get the width/height/codec. It may be possible but again you would have to modify it

**Comment by itzaks** [comment]
I see, I'll hack around and see what I can do. Thanks for your help!
