### ISSUE TITLE
Audio ALSA support

### ISSUE THREAD

**Issue by magdesign** [jvcleave/ofxOMXPlayer#101]
Since original omxplayer supports ALSA sound,
for example: omxplayer -o alsa:hw:1,0 /location/of/video.mp4

It would be amazing to get also ALSA support on ofxOMXPlayer.

**Comment by PTS93** [comment]
Oh wow, I totally missed that they implemented that! Big +1 for adding alsa support for ofxOMXPlayer. By far the biggest issue I usually have.

**Comment by magdesign** [comment]
I think this will never come :-(

**Comment by jvcleave** [comment]
@magdesign yes - I've been on other non-RPi projects so it's unlikely to come from me.

**Comment by jvcleave** [comment]
the way you can enable it is to use

`omxPlayer.engine.m_config_audio.device = "omx:alsa"; `

before calling omxPlayer.setup();

on my config is it currently causing errors and stopping video from playing but the component is passing. I don't know if I need other config tweaks in order to work as expected

**Comment by PTS93** [comment]
Odd but would definitely be great to have!
Main use is having an i2s audio hat or a usb audio interface.

**Comment by jvcleave** [comment]
ok - i do have a usb sound card so I can try that. It's probably just a matter of passing the correct hardware id

**Comment by jvcleave** [comment]
it does work   - use the syntax

```
omxPlayer.engine.m_config_audio.device = "omx:alsa";
omxPlayer.engine.m_config_audio.subdevice = "hw:1,0";


//works but sounded weird with my config
//omxPlayer.engine.m_config_audio.subdevice = "default"; 
```

**Comment by PTS93** [comment]
thats really great!
