### ISSUE TITLE
how to stop a loop?

### ISSUE THREAD

**Issue by nim4n** [jvcleave/ofxOMXPlayer#103]
Hi
I have regular loop in my application and some times I need to play another video just one time and after that I want to play my regular video loop. so is there a way to find out when a video is finished ? or is there a way to turn off the loop and start it again?

ps: I know I can create two object with two different setting to handle this situation.

**Comment by jvcleave** [comment]
There is `enableLooping()`, `disableLooping` and `isLoopingEnabled()`

see `example-playlist` for events on loop/finish

**Comment by nim4n** [comment]
thanks a lot !
