### ISSUE TITLE
videoPath?

### ISSUE THREAD

**Issue by prismspecs** [jvcleave/ofxOMXPlayer#108]
ofxOMXPlayerSettings settings;
settings.videoPath = "hd.mov";
settings.enableAudio = false;
omxPlayer.setup(settings);

Assuming my vid is at bin/data/hd.mov, should this work? I'm getting an error on load:

> [ error ] OMXReader::OpenFile - hd.mov 
> [notice ] bool ofxOMXPlayerEngine::didReadFile(bool): didOpenMovie TOOK 2 MS
> [warning] bool ofxOMXPlayerEngine::setup(ofxOMXPlayerSettings&): FAST PATH MOVE OPEN FAILED - LIKELY A STREAM, TRYING SLOW PATH
> [ error ] OMXReader::OpenFile - hd.mov 
> [notice ] bool ofxOMXPlayerEngine::didReadFile(bool): didOpenMovie TOOK 2 MS
> [ error ] omxReader open moviePath FAIL: hd.mov
> [ error ] bool ofxOMXPlayer::openEngine(int): engine->setup FAIL
> [ error ] ofTexture: allocate(): ofTextureData has 0 width and/or height: 0x0
> [ error ] ofTexture: getTextureData(): texture has not been allocated
>

**Comment by nununo** [comment]
I believe you must translate the path using ofToDataPath("hd.mov",true)
