### ISSUE TITLE
ofxOMXPlayer doesn't seem to work with threads

### ISSUE THREAD

**Issue by nununo** [jvcleave/ofxOMXPlayer#111]
Hello, I just posted in the OF forum a description of the problem. It affects both ofMoviePlayer and ofOMXPlayer:
https://forum.openframeworks.cc/t/loading-an-ofmovieplayer-in-a-thread-not-working-correctly/26770

Any thoughts on how I can make this work are very welcome!

Thanks in advance,
Nuno

**Comment by jvcleave** [comment]
Seems general/implementation specific so I'm closing this since the forum thread is a better place
