### ISSUE TITLE
Pause function working odd with non-textured video

### ISSUE THREAD

**Issue by demmaone** [jvcleave/ofxOMXPlayer#112]
Hi, I'm using "example-playback-control" and I manage to playback a 1080/18mbps video overclocking a PI3 but because I don't need to access pixels or do any operation with the content I want to use the direct mode (specially to avoid OC the PI) and got access to the pause function.
nextframe, randomseek and restart work perfect but when I try to pause the playback there is a short pause in the frame and then continues the playback, if I maintain the P key pressed it works like the nextframe function. Any suggestions?
Thanks in advance and congratulations for the great work.

**Comment by jvcleave** [comment]
Does it work fine with the Big Bunny movie?
