### ISSUE TITLE
onVideoLoop not called

### ISSUE THREAD

**Issue by neilmendoza** [jvcleave/ofxOMXPlayer#136]
onVideoLoop isn't called if I add my own listener. Might get some time this week to work out why...

**Comment by jvcleave** [comment]
are you adding it via ofxOMXPlayerSettings or later?

**Comment by jvcleave** [comment]
this seemed to work for me - haven't tried a network stream yet

https://github.com/jvcleave/ofxOMXPlayer/commit/3abddf039af83d09f00e01db1841f48f693bd561

**Comment by neilmendoza** [comment]
Great, thanks!

**Comment by jvcleave** [comment]
network stream seems to work as well so closing :)
