### ISSUE TITLE
Draw a video in non rectangular shape of the window

### ISSUE THREAD

**Issue by oomek** [jvcleave/ofxOMXPlayer#144]
Hi, I have several questions if I may:
1. Is it possible to draw the video window in non rectangular (perspective) shape providing 4 pairs of coordinates?
2. Can I integrate it with sfml-pi so the draw order is preserved? ie. draw some sfml objects, call ofApp.draw() and then draw the rest of sfml objects?
3. Is it possible somehow to get a GLuint of the currently decoded frame so I could draw it with Opengl with zero copy?

**Comment by jvcleave** [comment]
1. yes with texture mode
2. not familiar with sfml-pi
3. yes in texture mode see https://github.com/jvcleave/ofxOMXPlayer/blob/master/src/ofxOMXPlayer.h#L54

**Comment by oomek** [comment]
That's great, If only I could find a way to integrate it with SFML :P  not sure if it's actually possible

**Comment by oomek** [comment]
I'm not gonna lie t'm actually looking for a conventional c++ wrapper for the omxPlayer which would give me an access to the Gluint of the rendered frame as the current ffmpeg+mmal method we are using in our app based on the SFML framework has dreadful performance.

**Comment by oomek** [comment]
I'll dig through your code for inspiration maybe if you don't mind.

**Comment by jvcleave** [comment]
good luck - you can also check out hello_videocube if you want an alternative route

https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/hello_pi/hello_videocube

**Comment by oomek** [comment]
Thanks for the link. Unfortunately this example plays only raw h264 files without audio.
