### ISSUE TITLE
missing cairo.h

### ISSUE THREAD

**Issue by prismspecs** [jvcleave/ofxOMXPlayer#148]
/media/costarica/32gb/workbench32gb/of_v20190324_linux64gcc6_release/libs/openFrameworks/graphics/ofCairoRenderer.h:4:10: fatal error: cairo.h: No such file or directory
 #include "cairo.h"

Ubuntu Mate 18.10, tested with OF 10, 10.1, and nightly

**Comment by jvcleave** [comment]
That looks like a general OF related error not caused by this addon

**Comment by prismspecs** [comment]
Got it. I can only reproduce it when using ofxOMXPlayer so figured it might be because of the addon.

**Comment by jvcleave** [comment]
I actually ran across this on an OF project (not RPi/ofxOMXPlayer) but I think it was related to the ofxOpenCv addon. Might be worth a look

**Comment by fieldOfView** [comment]
Just in case someone finds this through a search engine: be sure to run the `install_depends.sh` script. I don't know why missing av libs would cause compilation to go haywire like this, but running that script fixed this exact issue for me.
