### ISSUE TITLE
can't get drawCropped to work

### ISSUE THREAD

**Issue by crx091081gb** [jvcleave/ofxOMXPlayer#154]
I don't seem to be able get drawCropped to produce anything but black output even when using the bunny mov.

**Comment by jvcleave** [comment]
Do you have textures enabled? I am pretty sure drawCropped only works in direct mode

**Comment by crx091081gb** [comment]
I'll try turning it off and working from the direct mode example.

**Comment by jvcleave** [comment]
with texture mode you should be able to use drawSubsection

```
omxPlayer.getTextureReference().drawSubsection(0, 0, 100, 100);
```

**Comment by jvcleave** [comment]
Didn't test the above but check this

https://openframeworks.cc//documentation/gl/ofTexture/#!show_drawSubsection

**Comment by crx091081gb** [comment]
Thanks. Just got it working in the direct mode example.... and yup works in application! Thanks.

Might try the subsection tip but I think I can get away without needing textures, was just considering whether to to run it through a shader and resample it but that looks a lot easier.
