### ISSUE TITLE
flickering and dropped frames

### ISSUE THREAD

**Issue by matttennie** [jvcleave/ofxOMXPlayer#16]
I'm seeing flickering when I play back a movie.  It looks like the picture offsets for 1 frame or so.  The picture also drops out to black screen every so often and stays that way for about 2 seconds at a time.

I'm playing back h264 1080p movies.  Is this the preferred codec?

Don't know if I should open another issue but;
 I also notice that the movie plays the correct speed the first time through but then plays at double speed when it starts over.  It continues to play at that doubled speed for each loop thereafter.

**Comment by urbanvisuals** [comment]
I was getting the same drop out to black frequently when playing in non-textured mode. It would only drop out when calling OMXplayer from OF, but not when I ran OMXPlayer directly from the command line. 

I've upped the video ram to 256MB and that seems to have fixed it.

**Comment by domsson** [comment]
Also having the speed problem. For me, it occurs in a situation where I have two players, each wrapped in an ofThread. Once I tell one player to pause and the other to play (via setPaused()), they start speeding up. First only for the first few seconds of playback, but the more often I switch, the longer the high-speed phase seems to become. Any idea what could be the cause or a workaround?
