### ISSUE TITLE
example-basic would not compile anymore

### ISSUE THREAD

**Issue by pikilipita** [jvcleave/ofxOMXPlayer#19]
Since I picked the new sources today ( 21 March 2014 ), the example-basic would not compile anymore.
I've copied the src and libs folders to addons/ofxOMXPlayer/
and the example-basic folder to apps/myApps.
When doing "make", I'm getting many errors like that one:
../../../addons/ofxOMXPlayer/src/ADDON_DEFINES.h:206:2: error: time_t does not name a type.

What is the (new) proper way to compile the examples?
Used to work fine with teh github version from a few weeks ago...

**Comment by sqrtmo** [comment]
Hello, I am new to OF
I am trying to build example-basic. My ofxOMXPlayer folder is in OF/addons.

`HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Compiling OF library for Release
make[1]: Entering directory '/home/pi/Documents/OF/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Done!
make[1]: Leaving directory '/home/pi/Documents/OF/libs/openFrameworksCompiled/project'


Compiling example-basic for Release
make[1]: Entering directory '/home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
Compiling /home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic/src/main.cpp
g++ -c -O3 -DNDEBUG -Wall -Werror=return-type -std=c++14 -DGCC_HAS_REGEX -march=armv6 -mfpu=vfp -mfloat-abi=hard -fPIC -ftree-vectorize -Wno-psabi -pipe -DOF_USING_GTK -DOF_USING_GTK -DOF_USING_MPG123 -DTARGET_RASPBERRY_PI -DSTANDALONE -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -fPIC -U_FORTIFY_SOURCE -Wall -ftree-vectorize -Wno-deprecated-declarations -Wno-sign-compare -Wno-unknown-pragmas -Wno-unused-function -Wno-unused-but-set-variable  -I/opt/vc/include -I/opt/vc/include/IL -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -pthread -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/AL -I/usr/include/arm-linux-gnueabihf -I/usr/include/rtaudio -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I../../../libs/glm/include -I../../../libs/glm/include/glm -I../../../libs/glm/include/glm/simd -I../../../libs/glm/include/glm/gtx -I../../../libs/glm/include/glm/detail -I../../../libs/glm/include/glm/gtc -I../../../libs/json/include -I../../../libs/kiss/include -I../../../libs/tess2/include -I../../../libs/utf8/include -I../../../libs/utf8/include/utf8 -I../../../libs/openFrameworks -I../../../libs/openFrameworks/gl -I../../../libs/openFrameworks/communication -I../../../libs/openFrameworks/app -I../../../libs/openFrameworks/math -I../../../libs/openFrameworks/3d -I../../../libs/openFrameworks/events -I../../../libs/openFrameworks/types -I../../../libs/openFrameworks/video -I../../../libs/openFrameworks/graphics -I../../../libs/openFrameworks/sound -I../../../libs/openFrameworks/utils -I/home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic/src -I/home/pi/Documents/OF/addons/ofxOMXPlayer/src -Isrc -MMD -MP -MF obj/linuxarmv6l/Release/src/main.d -MT obj/linuxarmv6l/Release/src/main.o -o obj/linuxarmv6l/Release/src/main.o -c /home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic/src/main.cpp
In file included from /home/pi/Documents/OF/addons/ofxOMXPlayer/src/OMXInitializer.h:4:0,
                 from /home/pi/Documents/OF/addons/ofxOMXPlayer/src/ofxOMXPlayer.h:4,
                 from /home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic/src/ofApp.h:4,
                 from /home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic/src/main.cpp:2:
/home/pi/Documents/OF/addons/ofxOMXPlayer/src/LIBAV_INCLUDES.h:22:40: fatal error: libavfilter/avfiltergraph.h: No such file or directory
  #include <libavfilter/avfiltergraph.h>
                                        ^
compilation terminated.
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:221: recipe for target 'obj/linuxarmv6l/Release/src/main.o' failed
make[1]: *** [obj/linuxarmv6l/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/pi/Documents/OF/addons/ofxOMXPlayer/example-basic'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
`
am I missing something?
