### ISSUE TITLE
add volume into ofxOMXPlayerSettings

### ISSUE THREAD

**Issue by Maigre** [jvcleave/ofxOMXPlayer#21]
Hi,
it's more an enhancement idea than an issue:
it would be great to have the volume added to the  ofxOMXPlayerSettings object
for two reason:
- to be able supply the initial volume with other settings on player setup (so we don't have to set it up after the player has already started)
- when using loadMovie(); the volume would be kept unchanged. For the moment when we load a new file, the volume reset automatically to 0.5 and that can be annoying (we have to set  again the volume to the desired value after every loadMovie)

In those 2 cases, we have to change the volume after the video start at volume 0.5
and that can produce sound glitches or unwanted sounds.

Thanks for your work !

Best Regards

**Comment by magdesign** [comment]
how could I change volume on runtime?
