### ISSUE TITLE
Threaded init routine for start playing new video file

### ISSUE THREAD

**Issue by adrchlik** [jvcleave/ofxOMXPlayer#29]
I usually play several small video loops at one time. When I start new video loop it freeze for a short time all currently playing videos, because the initialization of a new video takes a time.
Do you plan to do threaded version of initialization routine for start playing new video file ?

**Comment by jvcleave** [comment]
Looking at this again I am not sure threading it will save any time as the video can't open anyway until it gets the hints/info from libav

The texture isn't being regenerated unless the new video width/height are different and in that case it will again slow down

There may be possible speed ups in reusing the engine components but I think most of the efficiency around allocating textures is already in there

**Comment by jvcleave** [comment]
found a big bottleneck in the file probing (took 3 seconds off in example playlist when switching movies)

Didn't see any side effects in my testing but I put an #define in cause someone needs it

a0397ce7eb33719b64e582204929e43a35c24b28

**Comment by PTS93** [comment]
So the gap between files is also due to the time libav/ffmpeg needs to get the file info?
