### ISSUE TITLE
Frame flashes white at the end of a movie when looping first time through

### ISSUE THREAD

**Issue by sethismyfriend** [jvcleave/ofxOMXPlayer#32]
I have 5 or 6 movies compressed with Streamclip which are 6-30 seconds long and loop. They have black backgrounds and all of them seem to have one frame where it flashes white at the end of the first loop (second time through it doesn't do this). I'm not sure how to fix this or why it is happening - it would be better for me if it flashed black - I set the background to black. 

Any ideas on what I should be looking at? I think using h.264 via your recommendations should have done the trick for good compression.

**Comment by sethismyfriend** [comment]
For me there is one flash on the first loop - but adding audio did not resolve my problem. I used quicktime 7 and pasted an audio track on the timeline and saved the file. What format are your clips? I could try converting mine - not all of them flash so I'm trying to figure out if its related to the file format.

**Comment by jvcleave** [comment]
using MediaInfo (https://mediaarea.net/en/MediaInfo)  this is the output for my best video. I believe I had to use Compressor in order to get `GOP : N=1` (a keyframe every frame) but you may be able to set that option in Quicktime export

The file is much larger but plays back great

````
General
Complete name : /Volumes/Data/home/pi/videos/current/AirBallonTimecode.mov
Format : MPEG-4
Format profile : QuickTime
Codec ID : qt
File size : 521 MiB
Duration : 4mn 1s
Overall bit rate mode : Variable
Overall bit rate : 18.1 Mbps
Encoded date : UTC 2014-03-06 07:26:44
Tagged date : UTC 2014-03-06 07:26:47
Writing library : Apple QuickTime

Video
ID : 2
Format : AVC
Format/Info : Advanced Video Codec
Format profile : Main@L4.1
Format settings, CABAC : No
Format settings, ReFrames : 2 frames
Format settings, GOP : N=1
Codec ID : avc1
Codec ID/Info : Advanced Video Coding
Duration : 4mn 1s
Bit rate mode : Variable
Bit rate : 16.6 Mbps
Width : 1 280 pixels
Height : 720 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 25.000 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.720
Stream size : 477 MiB (92%)
Language : English
Encoded date : UTC 2014-03-06 07:26:37
Tagged date : UTC 2014-03-06 07:26:47
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709

Audio
ID : 1
Format : PCM
Format settings, Endianness : Little
Format settings, Sign : Signed
Codec ID : sowt
Duration : 4mn 1s
Bit rate mode : Constant
Bit rate : 1 536 Kbps
Channel(s) : 2 channels
Channel positions : Front: L R
Sampling rate : 48.0 KHz
Bit depth : 16 bits
Stream size : 44.2 MiB (8%)
Language : English
Encoded date : UTC 2014-03-06 07:26:37
Tagged date : UTC 2014-03-06 07:26:47
````

**Comment by cmarty** [comment]
Hi
I want to ask if is there any workaround to fix this first time loop white flash.
I converted tenth of video clips (8 - 30s long) from MJPEG to H246 and for the half of them there is this first time loop white flash. I have tried everything (different codec, containter, GOP each frame, silent audio track etc...) and can not get rid of this first loop white flash. I can not even find any connection between the working video clips and those with the white flash.
For converting from  mjpeg to h264 I use ffmpeg with the parameters:
<code>
ffmpeg -i $1 -vcodec libx264 -vpre libx264-hq -b 4000k -pass 1 -an $1p1
.mp4
</code>
<code>
ffmpeg -i $1 -vcodec libx264 -vpre libx264-hq -b 4000k -pass 2 -an $1.mp4
</code>
the example of mjpeg and h264 videos are here:
https://www.dropbox.com/sh/sd7rzqoq2xl8kda/AAABPe6Iku-HULWDhdaMZq3Da?dl=0

I use the ofxomxplayer from commit on 13.12.2014 0880b58 which works great for looping.
The next commit 54a16d8 from 26.12.2014 brings some stutter when looping after the first loop. The first loop white flash persist.

**Comment by Gorgull** [comment]
I agree with cmarty about the stutter happening with revision 54a16d8, and it seems like it's there since then. 
Any solution but reverting to the 7e0e8f5b revision?

**Comment by sethismyfriend** [comment]
I looked at the changes and between those revisions. At the bottom there is
a change to OMXVideo.cpp related to the timestamp.

Reading around it looks like hints.ptsinvalid gets set when the
(presentation timestamp) are not available to xbmc. I wonder if removing
this check and forcing OMX_IndexParamBrcmVideoTimestampFifo

When enabled, the timestamp fifo mode will change the way incoming
timestamps are associated with output images. In this mode the incoming
timestamps get used without re-ordering on output images.

I wonder if sometimes the codecs used before the `if hints.ptsinvalid` was
removed had valid presentation timestamps and now we are forcing it to use
decode timestamps which don't allow the frames to be reordered.

This is just a theory based on reading articles like [this one](
https://code.google.com/p/android/issues/detail?id=74356) which also use
the OMX player..


-------------
Seth Hunter
PhD, MIT Media Lab - Research Scientist at Intel Labs
website <http://www.perspectum.com/>  |  inspiration
<http://arplay.tumblr.com/> |  life
<http://flickr.com/photos/sethismyfriend/>
-------------

**Comment by jvcleave** [comment]
@sethismyfriend good point

An easy test would be to try a problematic video and set
```
timeStampMode.bEnabled = OMX_FALSE;
```

`OMXVideo.cpp` applies to Non-Texture mode and `OMXEGLImage.cpp` applies to Texture mode

**Comment by cmarty** [comment]
I think I found where the white flash problem is. 
In class ofxOMXPlayerEngine in function void ofxOMXPlayerEngine::Process().
When there is 
<code>
				omxReader.SeekTime(0 * 1000.0f, AVSEEK_FLAG_BACKWARD, &startpts);
				
				packet = omxReader.Read();
</code >
packet.pts and packet.dts aren't adjusted after loop with loop offset and this packet with pts and dts == 0 do this white flash in second loop.
I just simply comment the line <code> packet = omxReader.Read(); </code> and it helps.
Now I was able to move my working branch to your commit 5a11459 (9.Jan2015). But next commit a0397ce from (10.Jan 2015) produce next visual problem when looping.
It is due to the fact that when video starts the dts and pts are not == 0 and after the seek (loop) and adding loop_offset there is a gap in dts,pts  ordering.
What helps me with debuging is displaing the pts and dts in OMXPlayerVideoBase.cpp.
For test you can try video in my previous post.

**Comment by HakanL** [comment]
Hi, do we have a patch for this that solved the issue completely? I have the same problem, I play some h264 videos without looping (and with audio) and they all flash at the end. They are purchased videos (from atmosfx.com) so I'm not sure how they are mastered, but I have white flash/flicker at the end of each of them.

**Comment by jvcleave** [comment]
@HakanL nothing new. The example movies don't flash so it seems to vary with compression settings.

**Comment by sethismyfriend** [comment]
@HakanL if you revert to commit of ofxOMXPlayer

git reset --hard a0397ce7eb33719b64e582204929e43a35c24b28
nano ofxOMXPlayerEngine.cpp

and comment out the "packet= omxReader.Read();" line in the Process()
function, it may solve your flashing issue for some compressions.

I had 5 videos which I tried recompressing multiple times and could never
get rid of the flash, audio or not - so I tried the method above
recommended by @cmarty - and its working for my one off purposes.

It removed the flash for 4 out of 5 of my clips - after the first loop.

At this point it's a hack fix. If anyone finds the perfect compression
settings please post them in this thread and I'll try them on another fork.


-------------
Seth Hunter
PhD, MIT Media Lab - Research Scientist at Intel Labs
website <http://www.perspectum.com/>  |  inspiration
<http://arplay.tumblr.com/> |  life
<http://flickr.com/photos/sethismyfriend/>
-------------

**Comment by HakanL** [comment]
ok, thanks for the info. You said it removes the flash after the first loop, I don't loop my videos, does that mean the fix won't work for me?

**Comment by jvcleave** [comment]
going to do some updates soon in order to accommodate the upcoming OF 0.9. If anyone has videos they are able to send me that cause the white flash feel free to email them (or links to them) at jvcleave@gmail.com
