### ISSUE TITLE
Question: What does the amount of GPU split depend on?

### ISSUE THREAD

**Issue by PTS93** [jvcleave/ofxOMXPlayer#36]
In the README it says "GPU split set to 128 (may need to be higher for larger videos)". What exactly is the determining factor here? Simply size? Meaning a 4 minute video is fine with 128MB but an hour long video needs 256MB? Or is it bitrate and or framerate that dictates the size?

**Comment by jvcleave** [comment]
No - I don't keep any video frames in RAM on the addon side

I am just getting back into updating some stuff so closing this for organization/see what to do next but feel free to continue comments if you have questions
