### ISSUE TITLE
Q: How to clear the screen when done playing in non-textured mode

### ISSUE THREAD

**Issue by PTS93** [jvcleave/ofxOMXPlayer#37]
I would like to play a video in non-textured mode but when the video finishes the last frame is still visible and frames after that get drawn behind that last frame.
How do I tell ofxOMXPlayer to unload and or clear the screen?

**Comment by jvcleave** [comment]
you can now reposition with setDisplayRectForNonTexture

3cb1aeedbf5e2ce764baed8eee65c0207375d6da

**Comment by PTS93** [comment]
Oh thats great! I also found out that my issue was that I closed the player in the video end event. Closing it outside of that by for example a use input, properly removes the video from the screen.
