### ISSUE TITLE
ofxOMXPlayer.h: no such File

### ISSUE THREAD

**Issue by FlowBo** [jvcleave/ofxOMXPlayer#45]
i'm trying to compile one example but i always get the 
ofxOMXPlayer.h: no such File 
error
I could not find anything on the web so i ask you guy's what to do.
Thanks

**Comment by jvcleave** [comment]
Which example? Did you put ofxOMXPlayer in your openFrameworks addons folder?

**Comment by FlowBo** [comment]
yes i cloned the git to openframeworks/addons.
I tried 3 different examples:

openframeworks/addons/ofxomxplayer/example-shader
openframeworks/addons/ofxomxplayer/example-multiple-players
openframeworks/addons/ofxomxplayer/example-displayrect

always the same error.
i will attach an image of the exact error.
![img_2046](https://cloud.githubusercontent.com/assets/2551100/6225492/55cf7dd0-b68b-11e4-9d03-1b4d125215a9.JPG)

**Comment by jvcleave** [comment]
rename the folder to `ofxOMXPlayer` 

Linux is case-sensitive

**Comment by FlowBo** [comment]
Thanks! Now it's working!
