### ISSUE TITLE
getPixels() returns RGBA data

### ISSUE THREAD

**Issue by pikilipita** [jvcleave/ofxOMXPlayer#47]
I noticed this addon is using GL_RGBA format for the videos textures.
is there a reason not for using RGB format? Or is there a way to receive RGB formatted data when calling ofxOMXPlayer::getPixels() ?

**Comment by jvcleave** [comment]
It really comes down to creating the EGLImage that the egl_render will accept - I couldn't get anything else but GL_RGBA to work. From what I have read using GL_RGB won't actually save any memory if that is what you are looking for,

**Comment by pikilipita** [comment]
That's because the getPixels() function of the 'ofVideoPlayer' class returns an RGB format and I'm trying to keep my pixels manipulations code cross platform, in my case the raspberry and osx.
And yes, also because I tought it would save some RAM using RGB on the rpi.

**Comment by jvcleave** [comment]
yeah - search for GL_RGBA on this page - OpenGL seems to converted everything to it internally anyway

https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexImage2D.xml
