### ISSUE TITLE
video compression recomendations ...

### ISSUE THREAD

**Issue by eloimaduell** [jvcleave/ofxOMXPlayer#48]
Hi ! 

I've tried to follow the video compression recomendations ... i used MPEGStreamClip in an OSX Mavericks system.

I can't find any way of rendering an H264 codec + PCM audio ? 

Maybe my first question would be if the recomendation are for : Quicktime or MP4 file ? 
If i choose MP4 and X264 i just can choose MP4-AAC audio ...
If i choose MOV and X264 i just can choose Uncompressed, IMA4:1, MPEG4-AAC. Mpeg Layer2 ...
Is the Uncompressed option a PCM ?

Thanks for making this a bit clearer ...

**Comment by jvcleave** [comment]
Uncompressed is PCM
AAC is usually ok as well but has had issues with some HDMI TVs, Capture Devicees
