### ISSUE TITLE
Correct seeking or seek to beginning / restart movie

### ISSUE THREAD

**Issue by I33N** [jvcleave/ofxOMXPlayer#5]
This is more of an enhancement to:
- perform correct and fast seeking
- restart a movie from the beginning

I tried several way but I either ended without any seeking at all or with a 1-3 sec lag.

It would be at least nice to have a correct Stop/Play method that rewind the movie to the beginning without to much lag.

Any idea on the subject?

**Comment by magdesign** [comment]
We made a omxplayer-sync script which runs smoothly on RPI with omxplayer: https://github.com/turingmachine/omxplayer-sync

Now we try to adopt it to ofxOmxplayer. Play, Pause, Jump To Position, we will adopt to send over OSC. 

There is one Problem: In your fork of Omxplayer, we miss the seek function you see here:
https://github.com/popcornmix/omxplayer/blob/master/omxplayer.cpp#L1484

We usually do a 'Pause', then 'Jump To' and the xxxxxxx number to tell in milliseconds where to jump to
(see it here: https://github.com/turingmachine/omxplayer-sync/blob/master/omxplayer-sync#L248) and then we send a Play again.
Please implement the 'Jump To' function or even the whole dBus system into your fork!
So we can provide the sync-script also for openframeworks.

**Comment by jvcleave** [comment]
@magdesign there is a `seekToTimeInSeconds` and the `example-seeking`

**Comment by eloimaduell** [comment]
I''ve tried example-seeking but i got a break or stop on the video at each new seek position. As far as i've seen the seekToTimeInSeconds function does delete the current engine and creates a new one with the startTimeInSeconds specified. 

Is this the cause of the break or stop on the video when seeking ? 

@magdesign script works with the original omxplayer and he is able to do quite smooth frame seeking (enough to make a frame sync in an array of RPis quite nice ) is there a reason why we couldn't achieve this with ofxOMXPlayer ? 

or maybe i'm doing something wrong ?

**Comment by jvcleave** [comment]
Deleting the engine is how omxplayer does it as well

In profiling I found openEngine method is not really the bottleneck (around ~50ms as I recall) - the libav probing of the video was (around ~250ms and isn't typically needed unless it is for streams)

omxplayer doesn't have a texture mode which is the primary reason for this addon - non-texture mode/omxplayer is generally more performant (especially with > 720p resolutions)

The accuracy of the seeking is largely dependent on the container - h264 isn't great for this but it what works best for hardware decoding. You can get more accuracy by putting a keyframe on every frame - Apple Compressor does this well for me (the provided videos are not optimized for seeking as keyframes make the file much larger)

**Comment by eloimaduell** [comment]
Hi @jvcleave ! 

I tried to encode myself a 720p video in after effects, in h264 75% quality and a keyframe everyframe. The file is 30 seconds long and it's arround 60 Mb. With this video my seek times are much more reduced, arround half a second in texture mode.

What about this function from OMXReader ?
 OMXReader::SeekTime(int time, bool backwords, double *startpts)

Seems to seek without opening the engine ? Probably i'm missing something, so sorry for myself being obdurate and curious ... I can't understand why we need to open the engine for a seek :_( . I would love to see a similar functionality as in a desktop operating system ... please consider my opinion as a newbie on RPi and OMXPlayer ...

**Comment by jvcleave** [comment]
@eloimaduell there are existing packets, a clock, lots of OpenMax Components to deal with. Believe me I have tried everything that I know of/understand

In fact Desktop apps have the same issue when it comes to GPU decoding. I've looked at those implementations as well.

**Comment by eloimaduell** [comment]
Thanks a lot for the infos ... and sorry i didn't want to bother with newbie questions.
I appreciate your answer and get clear that it's not in any way, simple as i thought ...
