### ISSUE TITLE
Inverted Video playback when in textured mode

### ISSUE THREAD

**Issue by brendan87** [jvcleave/ofxOMXPlayer#55]
I'm running the examples from https://github.com/openFrameworks-arm/RaspberryPiGuideCAN and compiling them on for the Pi 2 before running. However, the omxPlayerTextured displays flipped videos. The non-textured example works fine though.

**Comment by brendan87** [comment]
Scratch that - this doesn't appear to be an issue on the latest repository (probably should have tried that before posting this). Still - for future noobs it might not hurt to update the link on the site? Aside from that, thanks for writing this addon for the pi :)

**Comment by nenadlazovic** [comment]
just got code from https://github.com/openFrameworks-arm/RaspberryPiGuideCAN dated nov 13, 2013, and video is inverted ...
what is the repo URL you used ?
thanks

**Comment by PTS93** [comment]
he probably updated the linked commit of ofxOMXPlayer in the creativeapplication git. Just pull the latest code from this repo and use it to replace this: https://github.com/openFrameworks-arm/RaspberryPiGuideCAN/tree/master/ofxAddons/ofxOMXPlayer
