### ISSUE TITLE
no audio output - [error] COMXAudioCodecOMX::GetChannelMap - FFmpeg reported 2 channels, but the layout contains 0 ignoring

### ISSUE THREAD

**Issue by lunchboxav** [jvcleave/ofxOMXPlayer#63]
Hi,

I encountered this error message when playing my video and I didn't hear any audio, though I've only compiled the example-basic app

[error] COMXAudioCodecOMX::GetChannelMap - FFmpeg reported 2 channels, but the layout contains 0 ignoring

I tried the gist here https://gist.github.com/jvcleave/4972661 but that doesn't solve the problem either. 

Do you have any suggestion how to playback video with audio? I use my headphone jack btw.

**Comment by lunchboxav** [comment]
apparently, I just need to disable audio from HDMI. sorry for this. consider this issue non exists.

**Comment by vberthiaume** [comment]
I just ran into this issue, and I need the sound to be sent through HDMI... I can't seem to reopen this issue, should I create a new one?

**Comment by jvcleave** [comment]
@vberthiaume did you try the gist above? Does omxplayer play through the HDMI?

**Comment by vberthiaume** [comment]
Ah, sorry I hadn't seen the gist.  Will try and report.
