### ISSUE TITLE
-lsmbclient and -lssh

### ISSUE THREAD

**Issue by pikilipita** [jvcleave/ofxOMXPlayer#79]
I just updated oofxomxplayer ot the latest sources.
When compiling, I'm hitting this error:
cannot find -lsmbclient 
cannot -lssh

Any suggestions?

**Comment by jvcleave** [comment]
yeah - I recompiled ffmpeg in trying to see if I could get optimizations. I will probably recompile without the smb/ssh requirements but until then this should work

`sudo apt-get install libsmbclient-dev libssh-dev`

**Comment by pikilipita** [comment]
Thanks, will try that

**Comment by jvcleave** [comment]
btw - I've started including the Makefiles for ffmpeg if you want to do it yourself
e.g
https://github.com/jvcleave/ofxOMXPlayer/blob/master/libs/linuxarmv6l/Makefile

**Comment by jvcleave** [comment]
fixed for arm6 here:
a50b7fc5f4dc987f9ee652dc90d535207d4a66cd
