### ISSUE TITLE
how to modify pixels 

### ISSUE THREAD

**Issue by dmcyang163** [jvcleave/ofxOMXPlayer#90]
in example-basic : 

void ofApp::update()
{
	
    //if(omxPlayer.isFrameNew())
	    {
    		ofLogVerbose("omxPlayer.isFrameNew() \n");
    // get pixel and do some modify
    		unsigned char* pPixel = omxPlayer.getPixels();
    		for(int i=0; i<100000; i++)
    		{
        			*(pPixel+i) = 0;
    		}
    	}
}

but have no effect, how to modify pixels? any suggestion? thks

**Comment by jvcleave** [comment]
you have to call updatePixels() 

see example-pixels 

https://github.com/jvcleave/ofxOMXPlayer/blob/master/example-pixels/src/ofApp.cpp

**Comment by dmcyang163** [comment]
thank you very much,  it really do, i got it
